### ISSUE TITLE
Spring module not works on Java 6

### ISSUE THREAD

**Issue by Zefling** [ic3fox/jawr-spring#2]
I have this error if I lunch a project on Java 6 : 

java.lang.UnsupportedClassVersionError: net/jawr/web/servlet/JawrSpringController : Unsupported major.minor version 51.0 (unable to load class net.jawr.web.servlet.JawrSpringController)

It is problematic, many server are still in 1.6

Best regards

**Comment by florianflad** [comment]
Same problem on our application.  
Is there a possiblity to port this to Java 1.6?

**Comment by ic3fox** [comment]
Hi,

The JIRA [JAWR-375](https://java.net/jira/browse/JAWR-375) has been created to track this issue.

Cheers,

**Comment by ic3fox** [comment]
Hi,

It is too much an effort regarding my spare time to be able to handle a java 6 port.
I would be glad to help anyone working on this, but I will not be able to do it myself.
Sorry about that.

Cheers,
